### ISSUE TITLE
Svrf SDK 3.0.1 no longer compiling

### ISSUE THREAD

**Issue by piemonte** [Svrf/svrf-ios-sdk#69] opened 2019-07-29 05:11 UTC
# Bug report

Hey Svrf,

I've been using SDK version '3.0.1' and today after installing one of my projects, it seems like the Svrf internal analytics framework updated. This shouldn't be a big deal except that it doesn't compile, breaking the current release.

```
 SPEC CHECKSUMS:
-  Analytics: 63744ad4afa65c3bcdcdb7a94b62515bde5b3900
+  Analytics: 77fd5fb102a4a5eedafa2c2b0245ceb7b7c15e45
```

/Bridge/Pods/SvrfSDK/SvrfSDK/Source/SvrfAnalyticsManager.swift:37:30: Value of optional type 'SEGAnalytics?' must be unwrapped to refer to member 'identify' of wrapped base type 'SEGAnalytics'
/Bridge/Pods/SvrfSDK/SvrfSDK/Source/SvrfAnalyticsManager.swift:37:30: Chain the optional using '?' to access member 'identify' only for non-'nil' base values
/Bridge/Pods/SvrfSDK/SvrfSDK/Source/SvrfAnalyticsManager.swift:37:30: Force-unwrap using '!' to abort execution if the optional value contains 'nil'
/Bridge/Pods/SvrfSDK/SvrfSDK/Source/SvrfAnalyticsManager.swift:43:22: Value of optional type 'SEGAnalytics?' must be unwrapped to refer to member 'track' of wrapped base type 'SEGAnalytics'
/Bridge/Pods/SvrfSDK/SvrfSDK/Source/SvrfAnalyticsManager.swift:43:22: Chain the optional using '?' to access member 'track' only for non-'nil' base values
/Bridge/Pods/SvrfSDK/SvrfSDK/Source/SvrfAnalyticsManager.swift:43:22: Force-unwrap using '!' to abort execution if the optional value contains 'nil'
/Bridge/Pods/SvrfSDK/SvrfSDK/Source/SvrfAnalyticsManager.swift:48:22: Value of optional type 'SEGAnalytics?' must be unwrapped to refer to member 'track' of wrapped base type 'SEGAnalytics'
/Bridge/Pods/SvrfSDK/SvrfSDK/Source/SvrfAnalyticsManager.swift:48:22: Chain the optional using '?' to access member 'track' only for non-'nil' base values
/Bridge/Pods/SvrfSDK/SvrfSDK/Source/SvrfAnalyticsManager.swift:48:22: Force-unwrap using '!' to abort execution if the optional value contains 'nil'

**Comment by AndreiEvstratenko** [comment] 2019-07-29 06:41
Hey, Patrick!

Thanks for letting us know.

I'll update you when I understand where's the problem

**Comment by AndreiEvstratenko** [comment] 2019-08-02 09:52
Hey!

We can't reproduce this issue. Could you update us with steps to reproduce, please?

cc @piemonte

**Comment by brentchow** [comment] 2019-08-07 19:13
I ran into this issue after running `pod update` which updated Analytics to 3.7

```
Installing Analytics 3.7.0 (was 3.6.10)
```

**Comment by brentchow** [comment] 2019-08-12 18:37
Closed by https://github.com/Svrf/svrf-ios-sdk/releases/tag/3.0.2

**Closed by brentchow** 2019-08-12 18:37 UTC
Labels: Component: iOS SDK, Priority: Critical, Type: Bug
